added css for immersive_reader button in modulesitems.less. KURSP399
matematikk-mooc/frontend pull request #148
Opened 2021-06-09 11:40 UTC by manilpit

2021-06-09 11:55 UTC, etsikt requested changes

2021-06-09 11:55 UTC, etsikt commented on src/css/framework/canvas-framework-newui.less
> +          // margin: 6px;
Hvorfor har du kommentar her?

2021-06-09 11:55 UTC, etsikt commented on src/css/modules/moduleitems.less
> +.fQfxa_dqAF.fQfxa_buuG {
Det kan se ut som dette er et klassenavn som er generert. Da er det en risiko for at den vil kunne endre seg. Kanskje den vil endre seg neste gang vi laster opp et nytt design. Finnes det ikke noe annet klassenavn e.l. vi kan bruke?

2021-06-09 11:55 UTC, etsikt commented on src/css/setup/mixins.less
> +
Her har du lagt til en blank linje....

2021-06-09 11:55 UTC, etsikt commented on src/js/modules/pages.js
> +      var buttonHtml = '<a class="btn immersive_reader_button" ';
Er ikke knappen der fra før? Må den legges til?

2021-06-10 07:22 UTC, manilpit commented on src/css/framework/canvas-framework-newui.less
> +          // margin: 6px;
Dette er forandringer som jeg hadde slettet men som ikke har kommet med.. Usikker på hvorfor ser på git push rutiner.

2021-06-10 07:22 UTC, manilpit commented on src/js/modules/pages.js
> +      var buttonHtml = '<a class="btn immersive_reader_button" ';
Dette er også forsøksvis roting som er slettet ved min utgave av branchen..

2021-06-10 07:26 UTC, manilpit commented on src/css/modules/moduleitems.less
> +.fQfxa_dqAF.fQfxa_buuG {
@erlendthune  mulig dette er sant, men jeg fant ingen annen metode å faktisk få endringer i cssen ut i designet. Andre klassenavn som ble forsøkt er i relasjon til "immersivereader" dette hadde ingen effekt.

2021-06-10 07:28 UTC, closed without merging